[versions]
kotlin = "2.1.21"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

[plugins]
dokka = "org.jetbrains.dokka:2.0.0"
gitSemVer = "org.danilopianini.git-sensitive-semantic-versioning-gradle-plugin:5.1.3"
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-qa = "org.danilopianini.gradle-kotlin-qa:0.86.2"
multiJvmTesting = "org.danilopianini.multi-jvm-test-plugin:3.2.4"
npm-publish = "org.danilopianini.npm.publish:4.0.4"
publishOnCentral = "org.danilopianini.publish-on-central:8.0.4"
taskTree = "com.dorongold.task-tree:4.0.1"
